name = "sqg_identity"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["SqgIdentity"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0"

[[require]]
name = "fourier_analysis"
git = "https://github.com/Brsanch/sqg-lean-proofs-fourier.git"
rev = "main"

[[lean_lib]]
name = "SqgIdentity"
